# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# see https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
  # Group all version-updates, except for Gardener-related ones. Gardener-components should receive their own PR this way. Security updates will
  # also still receive their own individual PRs.
    non-gardener-dependencies:
      applies-to: "version-updates"
      patterns:
      - "*"
      exclude-patterns:
      - "github.com/gardener*"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
