#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0
set -e

# For the test step concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.

cd test/integration/controller
if ! hash ginkgo; then
    # Install Ginkgo (test framework) to be able to execute the tests.
    echo "Fetching Ginkgo frawework"
    GO111MODULE=off go get -u github.com/onsi/ginkgo/ginkgo
    echo "Successfully fetched Ginkgo frawework"
fi

echo "Starting integration tests..."

ginkgo -v