apiVersion: v1
kind: Secret
metadata:
  name: core-openstack
  namespace: shoot--foobar--openstack
type: Opaque
data:
  domainName: domain
  tenantName: tenant
  username: user
  password: password
  authURL: keystoneURL # mandatory